# Generated by Django 5.0.6 on 2024-08-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailsubscription", name="confirmation_code",
        ),
    ]
