# Generated by Django 5.0.6 on 2024-08-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_emailsubscription_confirmation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherhistory",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
